---
title: "`cvCovEst`: Cross-Validated Covariance Matrix Estimation"
author: "[Philippe Boileau](https://pboileau.ca), Brian Collica, [Nima
  Hejazi](https://nimahejazi.org)"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
bibliography: ../inst/REFERENCES.bib
vignette: >
  %\VignetteIndexEntry{cvCovEst: Cross-Validated Covariance Matrix Estimation}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

## Background and Motivation

When the number of observations in a dataset far exceeds the number of
features, the estimator of choice for the covariance matrix is the sample
covariance matrix. It is an efficient estimator under minimal regularity
assumptions on the data generating distribution. In high-dimensional regimes,
however, this estimator leaves much to be desired. In this setting, the sample
covariance matrix is either singular, numerically unstable, or both, thereby
amplifying estimation error.

As high-dimensional data has become widespread, researchers have derived
many novel covariance matrix estimators to remediate the sample covariance
matrix’s deficiencies. These estimators come in many flavours, though most
are constructed by regularizing the sample covariance matrix, or through the
estimation of latent factors. A comprehensive review is provided by @fan2016.

This variety brings challenges, however. Identifying an "optimal" estimator
from among a collection of candidates is a non-trivial task.
Though data-driven approaches for selecting the optimal estimator from within
certain classes have been derived, the question of selecting an
estimator from among a diverse collection of candidates remains unaddressed.

We therefore offer just that: a general, cross-validation-based framework for
covariance matrix estimator selection in high dimensions. The
(high-dimensional) asymptotic optimality of selections are guaranteed by
extending the seminal work of @laan_dudoit:2003, @dudoit2005, and @vaart2006
on data-adaptive estimator selection to high-dimensional covariance matrix
estimation [@boileau2021]. The interested reader is invited to review
theoretical underpinnings of the method provided in @boileau2021 .


## Cross-validated Covariance Matrix Estimation

Let there be a high-dimensional dataset comprising $n$ realizations of $i.i.d$
$p$-length random vectors with a possibly nonparametric data-generating
distribution. Our goal is to estimate these random vectors' covariance matrix,
which may be accomplished using our general cross-validated estimator selection
framework.

Given a library of candidate estimators, a loss function, and a choice of
cross-validation scheme, `cvCovEst` will identify the asymptotically optimal
estimator of the covariance matrix from among all candidates. It subsequently
estimates this parameter using the selected candidate. An example is provided
below. Lists and brief descriptions of implemented candidate estimators, loss
functions, and cross-validation schemes are provided in the sequel.

```{r brief-example}
library(MASS)
library(cvCovEst)
set.seed(1584)

# generate a 50x50 covariance matrix with unit variances and off-diagonal
# elements equal to 0.5
sigma <- matrix(0.5, nrow = 50, ncol = 50) + diag(0.5, nrow = 50)

# sample 50 observations from multivariate normal with mean = 0, var = Sigma
dat <- mvrnorm(n = 50, mu = rep(0, 50), Sigma = sigma)

# run CV-selector
cv_cov_est_out <- cvCovEst(
    dat = dat,
    estimators = c(
      linearShrinkLWEst, denseLinearShrinkEst,
      thresholdingEst, poetEst, sampleCovEst
    ),
    estimator_params = list(
      thresholdingEst = list(gamma = c(0.2, 0.4)),
      poetEst = list(lambda = c(0.1, 0.2), k = c(1L, 2L))
    ),
    cv_loss = cvMatrixFrobeniusLoss,
    cv_scheme = "v_fold",
    v_folds = 5,
  )

# print the table of risk estimates
cv_cov_est_out$risk_df

# print a subset of the selected estimator's estimate
cv_cov_est_out$estimate[1:5, 1:5]
```

### Candidate Estimators

Covariance matrix estimators implemented in the `cvCovEst` package are
catalogued in the following table. These estimators are fed to the `cvCovEst`
function through the `estimators` argument as a vector. If these estimators
rely on hyperparameters, then they must be passed to the `estimator_params` as
a list. Depending on your assumptions --- or lack thereof --- about the true
covariance matrix, you may choose to use a subset of these estimators, or all
of them. They may also be used as standalone functions.

|Estimator | Implementation | Description |
|----------|----------|-------------|
| Sample covariance matrix | `sampleCovEst` | The sample covariance matrix. |
| Hard thresholding [@Bickel2008_thresh] | `thresholdingEst` | Applies a hard thresholding operator to the entries of the sample covariance matrix |
| SCAD thresholding [@rothman2009;@fan2001] | `scadEst` | Applies the SCAD thresholding operator to the entries of the sample covariance matrix.|
| Adaptive LASSO [@rothman2009] | `adaptiveLassoEst` | Applies the adaptive LASSO thresholding operator to the entries of the sample covariance matrix |
| Banding [@bickel2008_banding] | `bandingEst` | Replaces the sample covariance matrix's off-diagonal bands by zeros. |
| Tapering [@cai2010] | `taperingEst` | Tapers the sample covariance matrix's off-diagonal bands, eventually replacing them by zeros. |
| Optimal Linear Shrinkage [@Ledoit2004] | `linearShrinkLWEst` | Asymptotically optimal shrinkage of the sample covariance matrix towards the identity. |
| Linear Shrinkage [@Ledoit2004] | `linearShrinkEst` | Shrinkage of the sample covariance matrix towards the identity, but the shrinkage is controlled by a hyperparameter. |
| Dense Linear Shrinkage [@shafer2005] | `denseLinearShrinkEst` | Asymptotically optimal shrinkage of the sample covariance matrix towards a dense matrix whose diagonal elements are the mean of the sample covariance matrix's diagonal, and whose off-diagonal elements are the mean of the sample covariance matrix's off-diagonal elements. |
| Nonlinear Shrinkage [@Ledoit2020] | `nlShrinkLWEst` | Analytical estimator for the nonlinear shrinkage of the sample covariance matrix. |
| POET [@fan2013] | `poetEst` | An estimator based on latent variable estimation and thresholding. |
| Robust POET [@fan2018] | `robustPoetEst` | A robust (and more computationally taxing) take on the POET estimator. |


Note that `cvCovEst` only functions with estimators native to this package. If
you'd like to request a new one, please submit an
[issue](https://github.com/PhilBoileau/cvCovEst/issues).

### Loss Functions

Given a collection of candidate estimators, `cvCovEst` compares theirs
conditional cross-validated risks to identify the optimal selection. The loss
function used to compute these risks should reflect both aspects of the
data-generating distribution, and the goal of the estimation procedure. This
package currently implements three loss functions:

| Loss | Implementation | Description |
|------|----------------|-------------|
| Matrix-based Frobenius | `cvMatrixFrobeniusLoss` | The default, based on the Frobenius norm. Appropriate when the dataset's features are of similar magnitudes. |
| Variance-scaled matrix-based Frobenius | `cvScaledMatrixFrobeniusLoss` | A scaled version of the matrix-based Frobenius loss, where weights are the inverse of products from the sample covariance matrix's diagonal. Appropriate when the features of the dataset are of different magnitudes. |
| Observation-based Frobenius | `cvFrobeniusLoss` | Based on the Frobenius norm and the rank-1, observation-level estimates of the sample covariance matrix. Its selections are equivalent to that of the matrix-based Frobenius, though less computationally efficient. However, the optimality results of @boileau2021 rely on it. | 

The choice of loss function is set trough the `cv_loss` argument. Like the
candidate estimators, `cvCovEst` only supports loss functions implemented in
this package. Please submit suggestions to
[issue](https://github.com/PhilBoileau/cvCovEst/issues).

### Supported Cross-Validation Schemes

Two cross-validation schemes are currently supported by `cvCovEst`. If you'd
like us to consider implementing another, let us know by filing an
[issue](https://github.com/PhilBoileau/cvCovEst/issues).

| Scheme | Details |
|--------|---------|
| V-fold | To use V-fold cross-validation, set the `cv_scheme` argument in `cvCovEst` to `"v_fold"`, and set the number of folds through the `v_folds` argument. `cvCovEst` defaults to 5-fold cross-validation. |
| Monte-Carlo | To perform Monte-Carlo cross-validation, set the `cv_scheme` argument to `"mc"`. Set the proportion of data to be used in each validation set using the `mc_split` argument, and the number of iterations to perform with the `v_folds` argument. |


<!--
## Diagnostic Tools

A variety of summary and diagnostic functions are provided by the `cvCovEst`
package.

TODO

# Data Analysis Examples

TODO

## Simulated Data

## Single Cell Transcriptomic Data
-->

## References

